server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        git:
#          uri: file:///G:/microservices/microservices_workspace/microservice_interconnect/git-localconfig-repo
          refresh-rate: 1
        default-label: dev
        native:
          search-locations: file:///G:/microservices/microservices_workspace/microservice_interconnect
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: refresh
